// @generated
// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Events {
    #[prost(message, repeated, tag="1")]
    pub deposit_events: ::prost::alloc::vec::Vec<Deposit>,
    #[prost(message, repeated, tag="2")]
    pub withdraw_events: ::prost::alloc::vec::Vec<Withdraw>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Deposit {
    #[prost(string, tag="1")]
    pub owner: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub vault: ::prost::alloc::string::String,
    #[prost(uint64, tag="3")]
    pub amount: u64,
    #[prost(string, tag="4")]
    pub tx_hash: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Withdraw {
    #[prost(string, tag="1")]
    pub owner: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub vault: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub tx_hash: ::prost::alloc::string::String,
}
// @@protoc_insertion_point(module)
